<!DOCTYPE html>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
<link rel='dns-prefetch' href='https://d2bm7x1jqouzel.cloudfront.net' />
<link rel='dns-prefetch' href='//d3v4eglovri8yt.cloudfront.net' />
<link rel='stylesheet' href='../def.css' />

<title>My Account - Blue'ity Client Rips</title>
<meta name='viewport' content='width=device-width, initial-scale=1' />

<meta name='google-site-verification' content='K_niiTfCVi72gwvxK00O4NjsVybMutMUnc-ZnN6HUuA' />
</head>

<body>
    <header class="container">
        <span id='logo'><logo-blueityclientrips /></span> <a class="btn" href="../styles/school/videomaker/dummy.html" data-oghref="/go_full">MAKE A VIDEO</a>
    </header>
<main>
    <div class="panel account">
        <?php 
        echo "<p>", _GET[$this->name;] ,"</p>";
        ?>

        <h2>Videos</h2>
        <table>
            <tr>Name</tr>
            <thead>
                <?php 
                _GET[$this->myvideos;];
                ?>
            </thead>
        </table>
    </div>
</main>
<footer>
</footer>
</body>